language: node_js
node_js:
 - "5.10.1"
before_script:
  - npm run lint
  - cd test/sandbox
  - wget https://dl.dropboxusercontent.com/u/21095169/archive/sencha-extjs-6.0.1.250.tar.gz
  - tar -zxf sencha-extjs-6.0.1.250.tar.gz
  - wget https://dl.dropboxusercontent.com/u/21095169/archive/sencha-cmd-6.1.2.15.tar.gz
  - tar -zxf sencha-cmd-6.1.2.15.tar.gz
  - ./6.1.2.15/sencha app build
  - cd ../../
  - npm install mocha-phantomjs@4.0.2 mocha-phantomjs-core@2.0.1 phantomjs-prebuilt@2.1.7
  - npm run fix-deps
  - ./node_modules/.bin/phantomjs --version
  - npm start &
  - sleep 20
